[config]
schemaVersion = "0.0.1"

[package]
namespace = "SwiftCobra"
name = "SpeedLimit"
versionNumber = "0.1.4"
description = "Change Speed Limits"
websiteUrl = "https://github.com/SwiftCobra/SpeedLimitMod"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Cities2Modding-HookUI = "0.3.9"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" ]