//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class Bindings
{
	public static SpeedLimitToolActive: string = `SpeedLimitToolActive`;
	public static UnitSystem: string = `UnitSystem`;
	public static AverageSpeed: string = `AverageSpeed`;
	public static Name: string = `Name`;
	public static SetSpeedLimit: string = `SetSpeedLimit`;
	public static SelectTool: string = `SelectTool`;
	public static Reset: string = `Reset`;
}
